### ISSUE TITLE
Initial suggestions for plugin release

### ISSUE THREAD

**Issue by misraved** [ellisvalentiner/steampipe-plugin-weatherkit#10]
Thanks @ellisvalentiner for creating another awesome plugin. Great to see some amazing work around the weatherkit APIs.

The basic structure and results look good so far. While using the plugin, we did come up with a few suggestions based on our best practices (You can check them out here - https://steampipe.io/docs/develop/plugin-release-checklist#table-documentation):

- Could you please create a CHANGELOG file so that it will be easier to track the releases? A standard `md` file which includes the initial tables should suffice. You could use https://github.com/turbot/steampipe-plugin-vercel/blob/main/CHANGELOG.md#v001-2022-07-19 for reference.
- The slack channel in `docs/index.md` (https://github.com/ellisvalentiner/steampipe-plugin-weatherkit/blob/main/docs/index.md#get-involved) should be updated to use the latest link. You can use https://github.com/turbot/steampipe-plugin-aws/blob/main/docs/index.md#get-involved as a reference.
-  The configuration section in the `docs/index.md` file should be a replica of the .spc file. Currently, it is missing information on the `token` argument. 
- Can the config arguments be set in the form of environment variables? If yes i think we need to add a provision to handle them.
- Does the API support pagination, backoff and retry mechanism? Please refer https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion for more information. It might not since the API is still in beta state. We could add them back later when the API starts supporting them.
- Without setting the config arguments when I run the queries, I had the following observation -
```
> select
    as_of,
    temperature,
    condition_code
from weatherkit_current_weather
where latitude = '42.281' and longitude = '-83.743';
Error: rpc error: code = Internal desc = hydrate function getCurrentWeather failed with panic key_id (SQLSTATE HV000)

> select *
from weatherkit_availability
where latitude='42.281' and longitude='-83.743';
Error: rpc error: code = Internal desc = hydrate function listAvailability failed with panic key_id (SQLSTATE HV000)
```
Could we update the error message to be more helpful? You could refer https://github.com/turbot/steampipe-plugin-vercel/blob/main/vercel/utils.go#L37 for more information.
- For the table doc, docs/index.md, and README, could we update the query format to use newlines? It will enhance the readability. You can use https://github.com/turbot/steampipe-plugin-aws/blob/main/docs/tables/aws_s3_bucket.md as a reference.

I had a great time playing around with the tables. The results look great 👍 .

Please let us know in case you have questions about the above-mentioned suggestions. Looking forward to releasing it to the hub 😄 .

**Comment by ellisvalentiner** [comment]
@misraved I believe I've addressed the issues you mentioned, would you mind giving this another look?

**Comment by misraved** [comment]
Thanks @ellisvalentiner, I will give it another pass, believe this should be ready for release 😄.

**Comment by misraved** [comment]
@ellisvalentiner apologies for the delay, I reviewed the plugin, and all the issues have been addressed 👍 .

Could you please add a small note in `docs/index.md` pertaining to the usage of environment variables? You can refer https://github.com/turbot/steampipe-plugin-aws/blob/main/docs/index.md#credentials-from-environment-variables for more information. 

Apart from that, the plugin is ready for release. Great work 👍 .

**Comment by ellisvalentiner** [comment]
@misraved Done!

**Comment by misraved** [comment]
Thanks @ellisvalentiner for the quick turnaround 🚀 .
